config/routes.rb
Rails.application.routes.draw do
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "breweries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beer.rb
class Beer < ApplicationRecord
  include AverageRating

  belongs_to :brewery
  has_many :ratings, dependent: :destroy

  def to_s
    return "#{self.name}, #{self.brewery.name}"
  end
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include AverageRating

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers
end

app/models/concerns/average_rating.rb
module AverageRating extend ActiveSupport::Concern
  def average_rating
    ratings.average(:score)
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :beer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    admin_accounts = { 'pekka' => 'beer', 'arto' => 'foobar', 'matti' => 'ittam', 'vilma' => 'kangas' }

    authenticate_or_request_with_http_basic do |username, password|
      correct_password = admin_accounts[username]

      raise RuntimeError.new("Invalid credentials") if correct_password.nil? or correct_password != password

      return true
    end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[ show edit update destroy ]

  # GET /beers or /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1 or /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new

    set_form_data
  end

  # GET /beers/1/edit
  def edit
    @breweries = Brewery.all
    
    set_form_data
  end

  # POST /beers or /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully created." }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1 or /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully updated." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1 or /beers/1.json
  def destroy
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url, notice: "Beer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beer_params
      params.require(:beer).permit(:name, :style, :brewery_id)
    end

    def available_styles
      return ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
    end

    def set_form_data
      @breweries = Brewery.all
      @styles = available_styles
    end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :authenticate, only: %i[destroy]

  # GET /breweries or /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1 or /breweries/1.json
  def show; end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit; end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to brewery_url(@brewery), notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to brewery_url(@brewery), notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = Rating.all
  end

  def new
    @rating = Rating.new
    @beers = Beer.all
  end

  def create
    Rating.create params.require(:rating).permit(:beer_id, :score)

    redirect_to ratings_path
  end

  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    redirect_to ratings_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/beers/_beer.html.erb
<dl id="<%= dom_id beer %>">
  <dt>Name</dt>
  <dd><%= link_to beer.name, beer %></dd>
  <dt>Style:</dt>
  <dd><%= beer.style %></dd>
  <dt>Brewery:</dt>
  <dd><%= link_to beer.brewery.name, beer.brewery %></dd>
</dl>

app/views/beers/_form.html.erb
<%= form_with(model: beer) do |form| %>
  <% if beer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-2">
    <%= form.label :style %>
    <%= form.select :style, options_for_select(@styles) %>
  </div>

  <div class="mb-2">
    <%= form.label :brewery_id %>
    <%= form.select :brewery_id, options_from_collection_for_select(@breweries, :id, :name) %>
  </div>

  <%= form.submit submit_label, class: "btn" %>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render "form", beer: @beer, submit_label: "Edit beer" %>

<br>

<div>
  <%= link_to "Show this beer", @beer %> |
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beers</h1>

<%= link_to "New beer", new_beer_path %>

<div id="beers">
  <% @beers.each do |beer| %>
    <%= render beer %>
  <% end %>
</div>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render "form", beer: @beer, submit_label: "Create beer" %>

<br>

<div>
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @beer.name %></h1>

<dl>
    <dt>Style:</dt>
    <dd><%= @beer.style %></dd>
    <dt>Number of ratings:</dt>
    <dd>Beer has <%= pluralize(@beer.ratings.count, "rating") %></dd>
    <dt>Average rating:</dt>
    <dd>
      <% if @beer.ratings.empty? %>
        Beer has not yet been rated!
      <% else %>
        Beer's average rating is <%= @beer.average_rating %>
      <% end %>
    </dd>
    <dt>Brewery:</dt>
    <dd><%= link_to @beer.brewery.name, brewery_path(@beer.brewery) %></dd>
</dl>

<div>
  <%= link_to "Edit this beer", edit_beer_path(@beer) %> |
  <%= link_to "Back to beers", beers_path %>

  <%= button_to "Destroy this beer", @beer, method: :delete %>
</div>

app/views/breweries/_brewery.html.erb
<dl id="<%= dom_id brewery %>">
  <dt>Name:</dt>
  <dd><%= link_to brewery.name, brewery %></dd>
  <dt>Year:</dt>
  <dd><%= brewery.year %></dd>
</dl>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="mb-2">
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>


  <%= form.submit class: "btn" %>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Breweries</h1>

<%= link_to "New brewery", new_brewery_path %>

<div id="breweries">
  <% @breweries.each do |brewery| %>
    <%= render brewery %>
  <% end %>
</div>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @brewery.name %>, <i>established in <%= @brewery.year %></i></h1>

<dl>
  <dt>Number of ratings:</dt>
    <dd>Brewery has <%= pluralize(@brewery.ratings.count, "rating") %></dd>
  <dt>
    Average rating:
  </dt>
  <dd>
    <% if @brewery.ratings.empty? %>
      Brewery has not yet been rated!
    <% else %>
      Brewery's average rating is <%= @brewery.average_rating %>
    <% end %>
  </dd>
</dl>

Brewery has total of <%= pluralize(@brewery.beers.count, "beers") %>:

<ul>
<% @brewery.beers.each do |beer| %>
  <li><%= link_to beer.name, beer %></li>
<% end %>
</ul>

<div>
  <%= link_to "Edit this brewery", edit_brewery_path(@brewery) %> |
  <%= link_to "Back to breweries", breweries_path %>

  <%= button_to "Destroy this brewery", @brewery, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
      <div class="container">
        <a href="/" class="navbar__logo">
          🍻 Ratebeer 
        </a>

        <div class="navbar__links">
          <%= link_to "Breweries", breweries_path %>
          <%= link_to "Beers", beers_path %>
          <%= link_to "Ratings", ratings_path %>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
    <%= link_to rating.beer.name, rating.beer %> <%= rating.score %> <%= button_to 'Delete', rating, method: :delete, class: "btn btn--sm",  %> 
</div>

app/views/ratings/index.html.erb
<h1>Ratings</h1>

<p>
  <%= link_to "New rating", new_rating_path %>
</p>

<p>
  Total of <%= @ratings.count %> ratings:
</p>

<ul>
 <% @ratings.each do |rating| %>
   <li><%= render rating %></li>
 <% end %>
</ul>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= form_for(@rating) do |f| %>
  <div class="mb-2">
    <%= f.label :beer_id, "Beer" %>
    <%= f.select :beer_id, options_from_collection_for_select(@beers, :id, :to_s) %>
  </div>

  <div class="mb-2">
    <%= f.label :score, "Score" %>
    <%= f.number_field :score %>
  </div>
  <%= f.submit "Create rating", class: "btn" %>
<% end %>